"""Small dependency-free browser interface for the local application."""


def home_page() -> str:
    return """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Service Intelligence</title><style>
:root{--navy:#006b6b;--blue:#009999;--orange:#ec6602;--orange-dark:#b94f00;--pale:#e6f5f5;--line:#c9dddd;--text:#273536;--muted:#607071}
*{box-sizing:border-box}body{margin:0;background:#f4f7fa;color:var(--text);font:15px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif}
main{width:min(1040px,calc(100% - 32px));margin:48px auto}.hero{background:linear-gradient(135deg,#006b6b,#009999);color:white;border-radius:18px;padding:38px;box-shadow:0 14px 38px #006b6b24;border-bottom:5px solid var(--orange)}
h1{margin:0 0 8px;font-size:34px}.hero p{max-width:680px;margin:0;color:#dbe9f2;font-size:17px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin-top:22px}
.card{display:flex;flex-direction:column;background:white;border:1px solid var(--line);border-radius:14px;padding:22px;text-decoration:none;color:var(--text);box-shadow:0 8px 24px #006b6b0d}
.card:hover{border-color:var(--orange);transform:translateY(-2px)}.step{color:var(--orange-dark);font-weight:800;font-size:12px;text-transform:uppercase;letter-spacing:.08em}.card h2{color:var(--navy);margin:8px 0;font-size:21px}.card p{margin:0 0 18px;color:var(--muted);flex:1}.go{color:var(--orange-dark);font-weight:700}
.links{margin-top:20px;text-align:center}.links a{color:var(--blue);margin:0 10px}@media(max-width:760px){.grid{grid-template-columns:1fr}.hero{padding:28px}}
</style></head><body><main><section class="hero"><h1>Service Intelligence</h1><p>Turn signed work orders into auditable service events and quarterly management reports.</p></section>
<section class="grid">
<a class="card" href="/batch-upload"><span class="step">Step 1</span><h2>Upload work orders</h2><p>Extract and save up to 20 PDF work orders in one batch.</p><span class="go">Open batch upload -&gt;</span></a>
<a class="card" href="/review"><span class="step">Step 2</span><h2>Review events</h2><p>Correct extracted fields, approve records, and retain the audit history.</p><span class="go">Open review queue -&gt;</span></a>
<a class="card" href="/reports"><span class="step">Step 3</span><h2>Reports</h2><p>View availability metrics, trends, incidents, parts usage, and download PDF or Excel reports.</p><span class="go">Open reporting -&gt;</span></a>
<a class="card" href="/machines"><span class="step">Setup</span><h2>Customer &amp; machine register</h2><p>Maintain customer assignments, PCSNs, active dates, and reporting hours.</p><span class="go">Open register -&gt;</span></a>
<a class="card" href="/holidays"><span class="step">Setup</span><h2>Holiday calendar</h2><p>Review Kenya public holidays and add gazetted or organization closure dates.</p><span class="go">Open calendar -&gt;</span></a>
<a class="card" href="/report-profiles"><span class="step">Setup</span><h2>Working calendars</h2><p>Maintain named operating schedules used to calculate report availability.</p><span class="go">Open profiles -&gt;</span></a>
</section><div class="links"><a href="/docs">API documentation</a><a href="/v1/service-events">Saved-event JSON</a></div></main></body></html>"""


def machine_register_page() -> str:
    return """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Customer &amp; Machine Register - Service Intelligence</title><style>
:root{--navy:#006b6b;--blue:#009999;--orange:#ec6602;--pale:#e6f5f5;--line:#c9dddd;--text:#273536;--muted:#607071;--danger:#a52828;--success:#19723b}*{box-sizing:border-box}body{margin:0;background:#f5f8f8;color:var(--text);font:15px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif}main{width:min(1120px,calc(100% - 32px));margin:32px auto}.card{background:white;border:1px solid var(--line);border-radius:14px;padding:24px;box-shadow:0 10px 30px #006b6b12;border-top:4px solid var(--orange)}h1,h2{color:var(--navy)}h1{margin:0}h2{margin:30px 0 4px}.sub{margin:4px 0 20px;color:var(--muted)}.form{display:grid;grid-template-columns:2fr 1fr 1fr 1fr 1fr auto;gap:11px;align-items:end;padding:16px;background:var(--pale);border-radius:10px}.alias-form,.catalog-form{grid-template-columns:1fr 1fr auto auto}label{font-weight:700;color:var(--navy)}input{display:block;width:100%;margin-top:5px;padding:9px;border:1px solid var(--line);border-radius:7px;background:white}.check{display:flex;gap:8px;align-items:center;padding-bottom:8px}.check input{width:auto;margin:0}button{border:0;border-radius:8px;padding:10px 15px;background:var(--orange);color:white;font-weight:700;cursor:pointer}.secondary{background:var(--blue)}.danger{background:var(--danger)}.cancel{background:#647483}button:disabled{opacity:.45}.table-wrap{margin-top:20px;overflow:auto;border:1px solid var(--line);border-radius:9px}table{width:100%;border-collapse:collapse;background:white}th,td{padding:10px;border-bottom:1px solid var(--line);text-align:left}th{background:#f2f8f8;color:var(--navy);font-size:13px}.status{font-weight:700;color:var(--success)}.status.inactive{color:#7b8792}#message,#alias-message,#catalog-message{display:block;margin:12px 0;font-weight:650}.error{color:var(--danger)}.ok{color:var(--success)}.links{margin-top:20px}.links a{color:var(--blue);margin-right:18px}@media(max-width:900px){.form{grid-template-columns:1fr 1fr}}@media(max-width:560px){.form,.alias-form,.catalog-form{grid-template-columns:1fr}}
</style></head><body><main><section class="card"><h1>Customer &amp; Machine Register</h1><p class="sub">Registered machines contribute to quarterly availability even when they have no work orders.</p>
<form id="machine-form" class="form"><label>Customer<input id="customer" required maxlength="240"></label><label>PCSN<input id="pcsn" required pattern="[A-Za-z0-9]+" maxlength="40"></label><label>Quarterly hours<input id="hours" type="number" min="0.01" step="0.01" placeholder="Default 504"></label><label>Active from<input id="active-from" type="date"></label><label>Active until<input id="active-until" type="date"></label><label class="check"><input id="active" type="checkbox" checked>Active</label><button id="save" type="submit">Add machine</button><button id="cancel" type="button" class="cancel" hidden>Cancel edit</button></form>
<span id="message" role="status"></span><div class="table-wrap"><table><thead><tr><th>Customer</th><th>PCSN</th><th>Quarterly hours</th><th>Active from</th><th>Active until</th><th>Status</th><th></th></tr></thead><tbody id="machines"></tbody></table></div>
<h2>Customer aliases</h2><p class="sub">Map spelling or naming variations to one canonical customer so reports do not split the same site.</p>
<form id="alias-form" class="form alias-form"><label>Alias found in work orders<input id="alias-name" required maxlength="240" placeholder="Coast General Hospital"></label><label>Canonical customer name<input id="canonical-name" required maxlength="240" list="customer-options" placeholder="Coast General Teaching and Referral Hospital"><datalist id="customer-options"></datalist></label><button id="alias-save" type="submit">Add alias</button></form>
<span id="alias-message" role="status"></span><div class="table-wrap"><table><thead><tr><th>Alias</th><th>Canonical customer</th><th></th></tr></thead><tbody id="aliases"></tbody></table></div>
<h2>Product-code catalogue</h2><p class="sub">Product-code length varies. These prefixes are matched longest first so the PCSN serial-number boundary is never guessed.</p>
<form id="catalog-form" class="form catalog-form"><label>Product code<input id="product-code" required pattern="[A-Za-z0-9]+" maxlength="20" placeholder="H19"></label><label>Machine family<input id="machine-family" required maxlength="160" placeholder="TrueBeam Platform"></label><button id="catalog-save" type="submit">Add product code</button><button id="catalog-cancel" type="button" class="cancel" hidden>Cancel edit</button></form>
<span id="catalog-message" role="status"></span><div class="table-wrap"><table><thead><tr><th>Product code</th><th>Machine family</th><th></th></tr></thead><tbody id="catalog"></tbody></table></div>
<div class="links"><a href="/">Home</a><a href="/batch-upload">Batch upload</a><a href="/review">Review events</a><a href="/reports">Reports</a><a href="/docs">API documentation</a></div></section></main>
<script>
const form=document.getElementById('machine-form'),body=document.getElementById('machines'),message=document.getElementById('message'),save=document.getElementById('save'),cancel=document.getElementById('cancel'),aliasForm=document.getElementById('alias-form'),aliasBody=document.getElementById('aliases'),aliasMessage=document.getElementById('alias-message'),aliasSave=document.getElementById('alias-save'),customerOptions=document.getElementById('customer-options'),catalogForm=document.getElementById('catalog-form'),catalogBody=document.getElementById('catalog'),catalogMessage=document.getElementById('catalog-message'),catalogSave=document.getElementById('catalog-save'),catalogCancel=document.getElementById('catalog-cancel');let machines=[],aliases=[],catalog=[],editing=null,catalogEditing=null;
function msg(text,kind=''){message.textContent=text;message.className=kind}function value(id){return document.getElementById(id).value.trim()}function payload(){return{customer_name:value('customer'),pcsn:value('pcsn').toUpperCase(),quarterly_hours:value('hours')||null,active_from:value('active-from')||null,active_until:value('active-until')||null,active:document.getElementById('active').checked}}
function reset(){editing=null;form.reset();document.getElementById('active').checked=true;save.textContent='Add machine';cancel.hidden=true;msg('')}
function edit(machine){editing=machine.id;document.getElementById('customer').value=machine.customer_name;document.getElementById('pcsn').value=machine.pcsn;document.getElementById('hours').value=machine.quarterly_hours??'';document.getElementById('active-from').value=machine.active_from??'';document.getElementById('active-until').value=machine.active_until??'';document.getElementById('active').checked=machine.active;save.textContent='Save changes';cancel.hidden=false;window.scrollTo({top:0,behavior:'smooth'});msg('Editing '+machine.pcsn)}
function render(){body.replaceChildren();customerOptions.replaceChildren();[...new Set(machines.map(x=>x.customer_name))].sort().forEach(name=>{const option=document.createElement('option');option.value=name;customerOptions.append(option)});if(!machines.length){const row=document.createElement('tr'),cell=document.createElement('td');cell.colSpan=7;cell.textContent='No machines registered yet.';row.append(cell);body.append(row);return}machines.forEach(machine=>{const row=document.createElement('tr');[machine.customer_name,machine.pcsn,machine.quarterly_hours||'Default',machine.active_from||'—',machine.active_until||'—'].forEach(text=>{const cell=document.createElement('td');cell.textContent=text;row.append(cell)});const status=document.createElement('td');status.textContent=machine.active?'Active':'Inactive';status.className='status '+(machine.active?'':'inactive');row.append(status);const action=document.createElement('td'),button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='Edit';button.onclick=()=>edit(machine);action.append(button);row.append(action);body.append(row)})}
function renderAliases(){aliasBody.replaceChildren();if(!aliases.length){const row=document.createElement('tr'),cell=document.createElement('td');cell.colSpan=3;cell.textContent='No customer aliases configured.';row.append(cell);aliasBody.append(row);return}aliases.forEach(item=>{const row=document.createElement('tr');[item.alias_name,item.canonical_name].forEach(text=>{const cell=document.createElement('td');cell.textContent=text;row.append(cell)});const action=document.createElement('td'),button=document.createElement('button');button.type='button';button.className='danger';button.textContent='Remove';button.onclick=()=>removeAlias(item);action.append(button);row.append(action);aliasBody.append(row)})}
async function load(){const response=await fetch('/v1/machines');const data=await response.json();if(!response.ok)throw new Error(data.detail||'Could not load machines.');machines=data;render()}
async function loadAliases(){const response=await fetch('/v1/customer-aliases'),data=await response.json();if(!response.ok)throw new Error(data.detail||'Could not load customer aliases.');aliases=data;renderAliases()}
async function removeAlias(item){if(!confirm('Remove alias '+item.alias_name+'?'))return;const response=await fetch('/v1/customer-aliases/'+item.id,{method:'DELETE'});if(!response.ok){const data=await response.json();throw new Error(data.detail||'Could not remove alias.')}await loadAliases();aliasMessage.textContent='Alias removed.';aliasMessage.className='ok'}
function resetCatalog(){catalogEditing=null;catalogForm.reset();catalogSave.textContent='Add product code';catalogCancel.hidden=true;catalogMessage.textContent=''}
function editCatalog(item){catalogEditing=item.id;document.getElementById('product-code').value=item.product_code;document.getElementById('machine-family').value=item.machine_family;catalogSave.textContent='Save changes';catalogCancel.hidden=false;catalogMessage.textContent='Editing '+item.product_code}
function renderCatalog(){catalogBody.replaceChildren();catalog.forEach(item=>{const row=document.createElement('tr');[item.product_code,item.machine_family].forEach(text=>{const cell=document.createElement('td');cell.textContent=text;row.append(cell)});const action=document.createElement('td'),editButton=document.createElement('button'),deleteButton=document.createElement('button');editButton.type=deleteButton.type='button';editButton.className='secondary';editButton.textContent='Edit';editButton.onclick=()=>editCatalog(item);deleteButton.className='danger';deleteButton.textContent='Remove';deleteButton.onclick=()=>removeCatalog(item);action.append(editButton,' ',deleteButton);row.append(action);catalogBody.append(row)})}
async function loadCatalog(){const response=await fetch('/v1/product-catalog'),data=await response.json();if(!response.ok)throw new Error(data.detail||'Could not load product catalogue.');catalog=data;renderCatalog()}
async function removeCatalog(item){if(!confirm('Remove product code '+item.product_code+'? Unknown PCSNs using it will no longer be split into product code and serial number.'))return;const response=await fetch('/v1/product-catalog/'+item.id,{method:'DELETE'});if(!response.ok){const data=await response.json();throw new Error(data.detail||'Could not remove product code.')}await loadCatalog();await load();catalogMessage.textContent='Product code removed.';catalogMessage.className='ok'}
form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;save.disabled=true;msg('Saving...');try{const response=await fetch(editing?'/v1/machines/'+editing:'/v1/machines',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Could not save machine.');reset();await load();msg('Machine saved.','ok')}catch(error){msg(error.message,'error')}finally{save.disabled=false}});aliasForm.addEventListener('submit',async event=>{event.preventDefault();aliasSave.disabled=true;aliasMessage.textContent='Saving...';try{const response=await fetch('/v1/customer-aliases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({alias_name:value('alias-name'),canonical_name:value('canonical-name')})}),data=await response.json();if(!response.ok)throw new Error(data.detail||'Could not save alias.');aliasForm.reset();await loadAliases();aliasMessage.textContent='Customer alias saved.';aliasMessage.className='ok'}catch(error){aliasMessage.textContent=error.message;aliasMessage.className='error'}finally{aliasSave.disabled=false}});catalogForm.addEventListener('submit',async event=>{event.preventDefault();catalogSave.disabled=true;catalogMessage.textContent='Saving...';try{const response=await fetch(catalogEditing?'/v1/product-catalog/'+catalogEditing:'/v1/product-catalog',{method:catalogEditing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_code:value('product-code').toUpperCase(),machine_family:value('machine-family')})}),data=await response.json();if(!response.ok)throw new Error(data.detail||'Could not save product code.');resetCatalog();await loadCatalog();await load();catalogMessage.textContent='Product code saved.';catalogMessage.className='ok'}catch(error){catalogMessage.textContent=error.message;catalogMessage.className='error'}finally{catalogSave.disabled=false}});cancel.onclick=reset;catalogCancel.onclick=resetCatalog;Promise.all([load(),loadAliases(),loadCatalog()]).catch(error=>msg(error.message,'error'));
</script></body></html>"""


def holiday_calendar_page() -> str:
    return """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Holiday Calendar - Service Intelligence</title><style>
:root{--navy:#006b6b;--blue:#009999;--orange:#ec6602;--pale:#e6f5f5;--line:#c9dddd;--text:#273536;--muted:#607071;--danger:#a52828;--success:#19723b}*{box-sizing:border-box}body{margin:0;background:#f5f8f8;color:var(--text);font:15px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif}main{width:min(900px,calc(100% - 32px));margin:32px auto}.card{background:white;border:1px solid var(--line);border-radius:14px;padding:24px;box-shadow:0 10px 30px #006b6b12;border-top:4px solid var(--orange)}h1{color:var(--navy);margin:0}.sub{color:var(--muted);margin:5px 0 20px}.toolbar,.form{display:flex;gap:12px;align-items:end;padding:15px;background:var(--pale);border-radius:10px;margin-bottom:14px}.form label:first-child{flex:1}label{font-weight:700;color:var(--navy)}input{display:block;margin-top:5px;padding:9px;border:1px solid var(--line);border-radius:7px;background:white}button{border:0;border-radius:8px;padding:10px 15px;background:var(--orange);color:white;font-weight:700;cursor:pointer}.secondary{background:var(--blue)}.danger{background:var(--danger)}.cancel{background:#647483}.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:9px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid var(--line);text-align:left}th{background:#f2f8f8;color:var(--navy)}#message{display:block;margin:10px 0;font-weight:650}.error{color:var(--danger)}.ok{color:var(--success)}.links{margin-top:20px}.links a{color:var(--blue);margin-right:18px}@media(max-width:620px){.toolbar,.form{display:grid;grid-template-columns:1fr}}
</style></head><body><main><section class="card"><h1>Holiday Calendar</h1><p class="sub">Reports count 8 operating hours for each Monday–Friday, excluding the dates listed here. Standard Kenyan holidays are created automatically; add newly gazetted and organization-specific closure days.</p>
<div class="toolbar"><label>Calendar year<input id="year" type="number" min="2020" max="2100"></label><button id="load" type="button">Load year</button></div>
<form id="holiday-form" class="form"><label>Holiday name<input id="name" required maxlength="160"></label><label>Date<input id="date" type="date" required></label><button id="save" type="submit">Add holiday</button><button id="cancel" type="button" class="cancel" hidden>Cancel edit</button></form>
<span id="message" role="status"></span><div class="table-wrap"><table><thead><tr><th>Date</th><th>Holiday</th><th>Source</th><th></th></tr></thead><tbody id="holidays"></tbody></table></div>
<div class="links"><a href="/">Home</a><a href="/machines">Machine register</a><a href="/reports">Reports</a><a href="/docs">API documentation</a></div></section></main>
<script>
const year=document.getElementById('year'),loadButton=document.getElementById('load'),form=document.getElementById('holiday-form'),nameInput=document.getElementById('name'),dateInput=document.getElementById('date'),save=document.getElementById('save'),cancel=document.getElementById('cancel'),body=document.getElementById('holidays'),message=document.getElementById('message');let holidays=[],editing=null;year.value=new Date().getFullYear();
function msg(text,kind=''){message.textContent=text;message.className=kind}function reset(){editing=null;form.reset();save.textContent='Add holiday';cancel.hidden=true}function edit(item){editing=item.id;nameInput.value=item.name;dateInput.value=item.holiday_date;save.textContent='Save changes';cancel.hidden=false;msg('Editing '+item.name)}
function render(){body.replaceChildren();holidays.forEach(item=>{const row=document.createElement('tr');[item.holiday_date,item.name,item.source==='standard'?'Standard calendar':'Manual'].forEach(value=>{const cell=document.createElement('td');cell.textContent=value;row.append(cell)});const actions=document.createElement('td'),editButton=document.createElement('button'),deleteButton=document.createElement('button');editButton.type=deleteButton.type='button';editButton.textContent='Edit';editButton.className='secondary';editButton.onclick=()=>edit(item);deleteButton.textContent='Remove';deleteButton.className='danger';deleteButton.onclick=()=>remove(item);actions.append(editButton,' ',deleteButton);row.append(actions);body.append(row)})}
async function load(){msg('Loading...');const response=await fetch('/v1/holidays?year='+year.value),data=await response.json();if(!response.ok)throw new Error(data.detail||'Could not load holidays.');holidays=data;render();msg(holidays.length+' holidays loaded.','ok')}
async function remove(item){if(!confirm('Remove '+item.name+' from the operating calendar?'))return;const response=await fetch('/v1/holidays/'+item.id,{method:'DELETE'});if(!response.ok){const data=await response.json();throw new Error(data.detail||'Could not remove holiday.')}await load()}
form.addEventListener('submit',async event=>{event.preventDefault();const response=await fetch(editing?'/v1/holidays/'+editing:'/v1/holidays',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:nameInput.value.trim(),holiday_date:dateInput.value})}),data=await response.json();if(!response.ok){msg(data.detail||'Could not save holiday.','error');return}reset();year.value=data.holiday_date.slice(0,4);await load()});loadButton.onclick=()=>load().catch(error=>msg(error.message,'error'));cancel.onclick=reset;load().catch(error=>msg(error.message,'error'));
</script></body></html>"""


def report_profiles_page() -> str:
    return """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Working Calendars - Service Intelligence</title><style>
:root{--navy:#006b6b;--blue:#009999;--orange:#ec6602;--pale:#e6f5f5;--line:#c9dddd;--text:#273536;--muted:#607071;--danger:#a52828;--success:#19723b}*{box-sizing:border-box}body{margin:0;background:#f5f8f8;color:var(--text);font:15px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif}main{width:min(1000px,calc(100% - 32px));margin:32px auto}.card{background:white;border:1px solid var(--line);border-radius:14px;padding:24px;box-shadow:0 10px 30px #006b6b12;border-top:4px solid var(--orange)}h1{color:var(--navy);margin:0}.sub{color:var(--muted);margin:5px 0 20px}.form{display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto;gap:12px;align-items:end;padding:16px;background:var(--pale);border-radius:10px}.days{grid-column:1/-1;display:flex;gap:12px;flex-wrap:wrap}.days label{display:flex;gap:5px;align-items:center}.days input{width:auto;margin:0}label{font-weight:700;color:var(--navy)}input{display:block;width:100%;margin-top:5px;padding:9px;border:1px solid var(--line);border-radius:7px;background:white}.default{display:flex;gap:6px;align-items:center;padding-bottom:8px}.default input{width:auto;margin:0}button{border:0;border-radius:8px;padding:10px 15px;background:var(--orange);color:white;font-weight:700;cursor:pointer}.secondary{background:var(--blue)}.danger{background:var(--danger)}.cancel{background:#647483}.table-wrap{margin-top:18px;overflow:auto;border:1px solid var(--line);border-radius:9px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid var(--line);text-align:left}th{background:#f2f8f8;color:var(--navy)}#message{display:block;margin:10px 0;font-weight:650}.error{color:var(--danger)}.ok{color:var(--success)}.links{margin-top:20px}.links a{color:var(--blue);margin-right:18px}@media(max-width:750px){.form{grid-template-columns:1fr}.days{grid-column:1}}
</style></head><body><main><section class="card"><h1>Working Calendar Profiles</h1><p class="sub">Profiles define eligible weekdays and operating hours. Saved holidays are still excluded separately.</p>
<form id="profile-form" class="form"><label>Profile name<input id="name" required maxlength="120"></label><label>Start<input id="start" type="time" required value="08:00"></label><label>End<input id="end" type="time" required value="17:00"></label><label>Break (minutes)<input id="break" type="number" min="0" max="720" required value="60"></label><label class="default"><input id="default" type="checkbox">Default</label><div class="days" id="days"><strong>Working days:</strong><label><input type="checkbox" value="0" checked>Mon</label><label><input type="checkbox" value="1" checked>Tue</label><label><input type="checkbox" value="2" checked>Wed</label><label><input type="checkbox" value="3" checked>Thu</label><label><input type="checkbox" value="4" checked>Fri</label><label><input type="checkbox" value="5">Sat</label><label><input type="checkbox" value="6">Sun</label></div><button id="save" type="submit">Add profile</button><button id="cancel" type="button" class="cancel" hidden>Cancel edit</button></form>
<span id="message"></span><div class="table-wrap"><table><thead><tr><th>Name</th><th>Days</th><th>Window</th><th>Break</th><th>Hours/day</th><th></th></tr></thead><tbody id="profiles"></tbody></table></div>
<div class="links"><a href="/">Home</a><a href="/reports">Reports</a><a href="/holidays">Holiday calendar</a><a href="/docs">API documentation</a></div></section></main><script>
const form=document.getElementById('profile-form'),body=document.getElementById('profiles'),message=document.getElementById('message'),save=document.getElementById('save'),cancel=document.getElementById('cancel');let profiles=[],editing=null;const dayNames=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
function value(id){return document.getElementById(id).value}function msg(text,kind=''){message.textContent=text;message.className=kind}function payload(){return{name:value('name').trim(),working_days:[...document.querySelectorAll('#days input:checked')].map(x=>Number(x.value)),start_time:value('start'),end_time:value('end'),break_minutes:Number(value('break')),is_default:document.getElementById('default').checked}}
function reset(){editing=null;form.reset();document.querySelectorAll('#days input').forEach((x,i)=>x.checked=i<5);document.getElementById('start').value='08:00';document.getElementById('end').value='17:00';document.getElementById('break').value='60';save.textContent='Add profile';cancel.hidden=true;msg('')}
function edit(item){editing=item.id;document.getElementById('name').value=item.name;document.getElementById('start').value=item.start_time.slice(0,5);document.getElementById('end').value=item.end_time.slice(0,5);document.getElementById('break').value=item.break_minutes;document.getElementById('default').checked=item.is_default;document.querySelectorAll('#days input').forEach(x=>x.checked=item.working_days.includes(Number(x.value)));save.textContent='Save changes';cancel.hidden=false;msg('Editing '+item.name)}
function render(){body.replaceChildren();profiles.forEach(item=>{const row=document.createElement('tr');[item.name+(item.is_default?' (default)':''),item.working_days.map(x=>dayNames[x]).join(', '),item.start_time.slice(0,5)+'–'+item.end_time.slice(0,5),item.break_minutes+' min',item.daily_hours].forEach(text=>{const td=document.createElement('td');td.textContent=text;row.append(td)});const actions=document.createElement('td'),editButton=document.createElement('button'),removeButton=document.createElement('button');editButton.type=removeButton.type='button';editButton.className='secondary';editButton.textContent='Edit';editButton.onclick=()=>edit(item);removeButton.className='danger';removeButton.textContent='Remove';removeButton.disabled=item.is_default;removeButton.onclick=()=>remove(item);actions.append(editButton,' ',removeButton);row.append(actions);body.append(row)})}
async function load(){const response=await fetch('/v1/report-profiles'),data=await response.json();if(!response.ok)throw new Error(data.detail||'Could not load profiles.');profiles=data;render()}
async function remove(item){if(!confirm('Remove '+item.name+'?'))return;const response=await fetch('/v1/report-profiles/'+item.id,{method:'DELETE'});if(!response.ok){const data=await response.json();throw new Error(data.detail||'Could not remove profile.')}await load()}
form.addEventListener('submit',async event=>{event.preventDefault();const dataToSave=payload();if(!dataToSave.working_days.length){msg('Select at least one working day.','error');return}const response=await fetch(editing?'/v1/report-profiles/'+editing:'/v1/report-profiles',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(dataToSave)}),data=await response.json();if(!response.ok){msg(data.detail||'Could not save profile.','error');return}reset();await load();msg('Profile saved.','ok')});cancel.onclick=reset;load().catch(error=>msg(error.message,'error'));
</script></body></html>"""


def reports_page() -> str:
    return """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Service Reports - Service Intelligence</title><style>
:root{--navy:#006b6b;--blue:#009999;--orange:#ec6602;--orange-dark:#b94f00;--pale:#e6f5f5;--line:#c9dddd;--text:#273536;--muted:#607071;--danger:#a52828;--success:#19723b}
*{box-sizing:border-box}body{margin:0;background:#f4f7fa;color:var(--text);font:15px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif}
main{width:min(1180px,calc(100% - 32px));margin:32px auto}.card{background:white;border:1px solid var(--line);border-radius:14px;padding:24px;box-shadow:0 10px 30px #006b6b12;border-top:4px solid var(--orange)}
.top{display:flex;justify-content:space-between;align-items:flex-start;gap:18px}h1,h2{color:var(--navy)}h1{margin:0 0 4px}h2{font-size:19px;margin:28px 0 10px}.sub{margin:0;color:var(--muted)}
.form{display:grid;grid-template-columns:repeat(5,minmax(120px,1fr)) auto;gap:12px;align-items:end;margin-top:22px;padding:18px;background:var(--pale);border-radius:10px}label{font-weight:700;color:var(--navy)}select,input{display:block;width:100%;margin-top:5px;padding:9px;border:1px solid var(--line);border-radius:7px;background:white}
button,.button{border:0;border-radius:8px;padding:10px 15px;background:var(--orange-dark);color:white;font-weight:700;cursor:pointer;text-decoration:none;white-space:nowrap}.secondary{background:var(--blue)}button:disabled{opacity:.45;cursor:not-allowed}
#message{display:block;margin-top:12px;font-weight:650}.error{color:var(--danger)}.ok{color:var(--success)}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:22px}.metric{padding:17px;border:1px solid var(--line);border-radius:10px;background:#fff}.metric strong{display:block;color:var(--navy);font-size:25px}.metric span{color:var(--muted)}
.two{display:grid;grid-template-columns:1fr 1fr;gap:20px}table{width:100%;border-collapse:collapse;background:white}th,td{padding:10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{color:var(--navy);background:#f7f9fb;font-size:13px}.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:9px}.empty{color:var(--muted);font-style:italic}.links{margin-top:24px}.links a{color:var(--blue);margin-right:18px}#report[hidden]{display:none}.trend-wrap{border:1px solid var(--line);border-radius:10px;padding:14px;overflow:auto;background:#fff}.trend-legend{display:flex;gap:20px;color:var(--muted);font-size:13px;margin-bottom:8px}.swatch{display:inline-block;width:13px;height:4px;margin-right:5px;vertical-align:middle}.swatch.uptime{background:var(--blue)}.swatch.downtime{background:var(--orange)}#trend-chart{width:100%;min-width:620px;height:250px;display:block}.trend-note{color:var(--muted);font-size:13px;margin:7px 0 0}
@media(max-width:820px){.form,.metrics,.two{grid-template-columns:1fr}.top{display:block}.top .button{display:inline-block;margin-top:12px}}
</style></head><body><main><section class="card"><div class="top"><div><h1>Service Report</h1><p class="sub">Built from approved stored service events and registered machines.</p></div><a class="button secondary" href="/">Home</a></div>
<form id="report-form" class="form"><label>Period type<select id="period-type"><option value="quarter">Quarter</option><option value="custom">Custom dates</option></select></label><label class="quarter-field">Year<input id="year" type="number" min="2020" max="2100" required></label><label class="quarter-field">Quarter<select id="quarter"><option value="1">Q1</option><option value="2">Q2</option><option value="3">Q3</option><option value="4">Q4</option></select></label><label class="date-field" hidden>Start date<input id="start-date" type="date"></label><label class="date-field" hidden>End date<input id="end-date" type="date"></label><label>Working calendar<select id="profile" required></select></label><label>Trend grouping<select id="trend-interval"><option value="month">Monthly</option><option value="quarter">Quarterly</option></select></label><label>Customer filter<input id="site" list="site-options" placeholder="All customers"><datalist id="site-options"></datalist></label><label>PCSN filter<input id="pcsn" list="pcsn-options" pattern="[A-Za-z0-9]+" placeholder="All machines"><datalist id="pcsn-options"></datalist></label><button id="generate" type="submit">Generate report</button></form>
<span id="message" role="status"></span><section id="report" hidden><div class="metrics"><div class="metric"><strong id="events">0</strong><span>Events in period</span></div><div class="metric"><strong id="machines">0</strong><span>Machines (PCSNs)</span></div><div class="metric"><strong id="basis">-</strong><span>Total fleet basis (h)</span></div><div class="metric"><strong id="unplanned">0.00</strong><span>Unplanned downtime (h)</span></div><div class="metric"><strong id="uptime">-</strong><span>Fleet uptime</span></div><div class="metric"><strong id="total">0.00</strong><span>Reported downtime (information only)</span></div></div>
<h2>Availability trend</h2><div class="trend-wrap"><div class="trend-legend"><span><i class="swatch uptime"></i>Uptime (%)</span><span><i class="swatch downtime"></i>Unplanned downtime (h)</span></div><svg id="trend-chart" viewBox="0 0 1000 250" role="img" aria-label="Uptime and downtime trend"></svg><p class="trend-note">Downtime bars use their own scale; exact values are shown below.</p></div><div class="table-wrap"><table><thead><tr><th>Period</th><th>Machines</th><th>Events</th><th>Corrective</th><th>Downtime (h)</th><th>Basis (h)</th><th>Uptime</th></tr></thead><tbody id="trend-table"></tbody></table></div>
<h2>Machine availability</h2><div class="table-wrap"><table><thead><tr><th>PCSN</th><th>Customer</th><th>Events</th><th>Corrective</th><th>Downtime</th><th>Basis</th><th>Uptime</th></tr></thead><tbody id="machines-table"></tbody></table></div>
<h2>Customer availability</h2><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Machines</th><th>Events</th><th>Downtime</th><th>Basis</th><th>Uptime</th></tr></thead><tbody id="sites-table"></tbody></table></div>
<div class="two"><section><h2>Service types</h2><div class="table-wrap"><table><thead><tr><th>Type</th><th>Count</th><th>Downtime</th></tr></thead><tbody id="service-types"></tbody></table></div></section><section><h2>Fault categories</h2><div class="table-wrap"><table><thead><tr><th>Category</th><th>Count</th><th>Downtime</th></tr></thead><tbody id="faults"></tbody></table></div></section></div>
<h2>Interventions</h2><div class="table-wrap"><table><thead><tr><th>Intervention</th><th>Count</th><th>Downtime</th></tr></thead><tbody id="interventions"></tbody></table></div>
<h2>Incidents</h2><div class="table-wrap"><table><thead><tr><th>Work order</th><th>Date</th><th>PCSN</th><th>Type</th><th>Issue</th><th>Intervention</th><th>Downtime</th><th>Uptime impact</th></tr></thead><tbody id="incidents"></tbody></table></div>
<div class="two"><section><h2>Parts used</h2><div class="table-wrap"><table><thead><tr><th>Part</th><th>Description</th><th>Qty</th><th>Work orders</th></tr></thead><tbody id="parts"></tbody></table></div></section><section><h2>Repeat issues</h2><div class="table-wrap"><table><thead><tr><th>PCSN</th><th>Issue</th><th>Count</th><th>Work orders</th></tr></thead><tbody id="repeats"></tbody></table></div></section></div>
<h2>Review notes</h2><ul id="notes"></ul><button id="pdf" type="button">Download PDF</button> <button id="xlsx" class="secondary" type="button">Download Excel</button></section><div class="links"><a href="/machines">Machine register</a><a href="/report-profiles">Working calendars</a><a href="/batch-upload">Batch upload</a><a href="/review">Review events</a><a href="/docs">API documentation</a></div></section></main>
<script>
const form=document.getElementById('report-form'),message=document.getElementById('message'),report=document.getElementById('report'),generate=document.getElementById('generate'),pdf=document.getElementById('pdf'),xlsx=document.getElementById('xlsx');
const now=new Date();document.getElementById('year').value=now.getFullYear();document.getElementById('quarter').value=String(Math.floor(now.getMonth()/3)+1);
const periodType=document.getElementById('period-type'),yearInput=document.getElementById('year'),quarterInput=document.getElementById('quarter'),startInput=document.getElementById('start-date'),endInput=document.getElementById('end-date');
function periodMode(){const custom=periodType.value==='custom';document.querySelectorAll('.quarter-field').forEach(item=>item.hidden=custom);document.querySelectorAll('.date-field').forEach(item=>item.hidden=!custom);yearInput.required=!custom;quarterInput.required=!custom;startInput.required=custom;endInput.required=custom}periodType.addEventListener('change',periodMode);periodMode();
let lastRequest=null;function msg(text,kind=''){message.textContent=text;message.className=kind}
function options(id,values){const list=document.getElementById(id);list.replaceChildren();values.forEach(value=>{const option=document.createElement('option');option.value=value;list.append(option)})}
async function loadOptions(){try{const [filterResponse,profileResponse]=await Promise.all([fetch('/v1/reports/filter-options'),fetch('/v1/report-profiles')]);if(filterResponse.ok){const data=await filterResponse.json();options('site-options',data.sites);options('pcsn-options',data.pcsns)}if(profileResponse.ok){const profiles=await profileResponse.json(),select=document.getElementById('profile');select.replaceChildren();profiles.forEach(item=>{const option=document.createElement('option');option.value=item.id;option.textContent=item.name+' · '+item.daily_hours+' h/day';option.selected=item.is_default;select.append(option)})}}catch(_error){}}
loadOptions();
function body(){const site=document.getElementById('site').value.trim(),pcsn=document.getElementById('pcsn').value.trim(),custom=periodType.value==='custom';return{year:custom?null:Number(yearInput.value),quarter:custom?null:Number(quarterInput.value),start_date:custom?startInput.value:null,end_date:custom?endInput.value:null,report_profile_id:Number(document.getElementById('profile').value),site_name:site||null,pcsn:pcsn||null}}
function cell(row,value){const td=document.createElement('td');td.textContent=value??'-';row.append(td)}
function rows(id,data,columns,empty){const tbody=document.getElementById(id);tbody.replaceChildren();if(!data.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=columns.length;td.textContent=empty;td.className='empty';tr.append(td);tbody.append(tr);return}data.forEach(item=>{const tr=document.createElement('tr');columns.forEach(column=>cell(tr,typeof column==='function'?column(item):item[column]));tbody.append(tr)})}
function percent(value){return value===null?'-':value+'%'}
function trendRequest(request,period){return{start_date:period.start_date,end_date:period.end_date,interval:document.getElementById('trend-interval').value,report_profile_id:request.report_profile_id,site_name:request.site_name,pcsn:request.pcsn}}
function drawTrend(points){const svg=document.getElementById('trend-chart');svg.replaceChildren();const ns='http://www.w3.org/2000/svg',w=1000,h=250,left=55,right=20,top=20,bottom=48,plotW=w-left-right,plotH=h-top-bottom,maxDown=Math.max(1,...points.map(x=>Number(x.unplanned_downtime_hours)));function add(name,attrs,text){const node=document.createElementNS(ns,name);Object.entries(attrs).forEach(([key,value])=>node.setAttribute(key,value));if(text!==undefined)node.textContent=text;svg.append(node);return node}for(let tick=0;tick<=4;tick++){const y=top+plotH-(tick/4)*plotH;add('line',{x1:left,y1:y,x2:w-right,y2:y,stroke:'#dbe5e5','stroke-width':1});add('text',{x:left-8,y:y+4,'text-anchor':'end',fill:'#607071','font-size':11},String(tick*25))}if(!points.length){add('text',{x:w/2,y:h/2,'text-anchor':'middle',fill:'#607071'},'No trend data.');return}const step=plotW/points.length,barW=Math.min(45,step*.45),linePoints=[];points.forEach((item,index)=>{const x=left+step*(index+.5),down=Number(item.unplanned_downtime_hours),uptime=item.uptime_percent===null?null:Number(item.uptime_percent),barH=(down/maxDown)*plotH;add('rect',{x:x-barW/2,y:top+plotH-barH,width:barW,height:barH,fill:'#ec6602',opacity:.78,rx:2});if(uptime!==null)linePoints.push(`${x},${top+plotH-(uptime/100)*plotH}`);add('text',{x,y:h-21,'text-anchor':'middle',fill:'#607071','font-size':11},item.period.label);});if(linePoints.length>1)add('polyline',{points:linePoints.join(' '),fill:'none',stroke:'#009999','stroke-width':3});linePoints.forEach(point=>{const [x,y]=point.split(',');add('circle',{cx:x,cy:y,r:4,fill:'#009999',stroke:'#fff','stroke-width':2})})}
async function renderTrend(request,period){const response=await fetch('/v1/reports/trends/stored',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(trendRequest(request,period))}),data=await response.json();if(!response.ok)throw new Error(data.detail||`HTTP ${response.status}`);drawTrend(data.points);rows('trend-table',data.points,[x=>x.period.label,'machine_count','events','corrective_events','unplanned_downtime_hours','working_hours_basis',x=>percent(x.uptime_percent)],'No trend data.');}
function render(data){document.getElementById('events').textContent=data.events_in_period;document.getElementById('machines').textContent=data.machine_count;document.getElementById('basis').textContent=data.working_hours_basis??'-';document.getElementById('unplanned').textContent=data.unplanned_downtime_hours;document.getElementById('uptime').textContent=percent(data.uptime_percent);document.getElementById('total').textContent=data.total_reported_downtime_hours;
rows('machines-table',data.machine_breakdown,['pcsn','site_name','event_count','corrective_event_count','unplanned_downtime_hours','working_hours_basis',x=>percent(x.uptime_percent)],'No machines match this selection.');rows('sites-table',data.site_breakdown,['site_name','machine_count','event_count','unplanned_downtime_hours','working_hours_basis',x=>percent(x.uptime_percent)],'No customers match this selection.');
rows('service-types',data.service_type_breakdown,['label','count','downtime_hours'],'No service events in this period.');rows('faults',data.fault_category_breakdown,['label','count','downtime_hours'],'No fault categories.');rows('interventions',data.intervention_breakdown,['label','count','downtime_hours'],'No interventions recorded.');
rows('incidents',data.incidents,['work_order_number',x=>x.service_date?new Date(x.service_date).toLocaleString():'-','pcsn','service_type','issue','intervention','downtime_hours',x=>x.included_in_uptime?'Yes':'No'],'No incidents in this period.');rows('parts',data.parts_used,['part_number','description','quantity',x=>x.work_order_numbers.join(', ')],'No parts recorded.');rows('repeats',data.repeat_issues,['pcsn','issue','occurrences',x=>x.work_order_numbers.join(', ')],'No repeat issues detected.');
const notes=document.getElementById('notes');notes.replaceChildren();(data.review_notes.length?data.review_notes:['No review notes.']).forEach(value=>{const li=document.createElement('li');li.textContent=value;notes.append(li)});report.hidden=false}
form.addEventListener('submit',async event=>{event.preventDefault();generate.disabled=true;report.hidden=true;msg('Generating report...');lastRequest=body();try{const response=await fetch('/v1/reports/quarterly/stored',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lastRequest)});const data=await response.json();if(!response.ok)throw new Error(data.detail||`HTTP ${response.status}`);render(data);await renderTrend(lastRequest,data.period);msg(`${data.period.label} report generated.`,'ok')}catch(error){msg(error.message,'error')}finally{generate.disabled=false}});
pdf.addEventListener('click',async()=>{if(!lastRequest)return;pdf.disabled=true;msg('Preparing PDF...');try{const response=await fetch('/v1/reports/quarterly/stored/pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lastRequest)});if(!response.ok){const data=await response.json();throw new Error(data.detail||`HTTP ${response.status}`)}const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=lastRequest.start_date?`service-report-${lastRequest.start_date}-to-${lastRequest.end_date}.pdf`:`service-report-Q${lastRequest.quarter}-${lastRequest.year}.pdf`;a.click();URL.revokeObjectURL(url);msg('PDF downloaded.','ok')}catch(error){msg(error.message,'error')}finally{pdf.disabled=false}});
xlsx.addEventListener('click',async()=>{if(!lastRequest)return;xlsx.disabled=true;msg('Preparing Excel workbook...');try{const response=await fetch('/v1/reports/quarterly/stored/xlsx',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lastRequest)});if(!response.ok){const data=await response.json();throw new Error(data.detail||`HTTP ${response.status}`)}const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=lastRequest.start_date?`service-report-${lastRequest.start_date}-to-${lastRequest.end_date}.xlsx`:`service-report-Q${lastRequest.quarter}-${lastRequest.year}.xlsx`;a.click();URL.revokeObjectURL(url);msg('Excel workbook downloaded.','ok')}catch(error){msg(error.message,'error')}finally{xlsx.disabled=false}});
</script></body></html>"""
